server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andrerequejo/springboot-microservices/tree/master/springboot-microservices-configuration/configuration-cloudclient
